# 应用配置
spring:
  # Redis配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口
    port: 6379
    # Redis数据库索引
    database: 0
    # Redis操作超时时间
    timeout: 3000ms
    # Redis连接池配置
    pool:
      # 最大活动连接数
      max-active: 8
      # 最大空闲连接数
      max-idle: 8
      # 最小空闲连接数
      min-idle: 0
      # 获取连接最大等待时间
      max-wait: 1000ms
